spring:
  datasource:
    username: root
    password: dustn@@0317
    url: "jdbc:mysql://localhost/peacizen?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      show-sql: true
      hibernate:
        format-sql: true
        ddl-auto: none

    logging:
      level:
        org:
          hibernate:
            SQL: DEBUG
            type: trace